DemoMVC/Models/Entities/Person.cs
namespace DemoMVC.Models.Entities{

using System.ComponentModel.DataAnnotations;

public class Person {
    [Key]
    public required string  PersonId { get; set; }

    public required string HoTen{ get; set; }

    public string? QueQuan   { get; set; }
}
}

DemoMVC/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DemoMVC.Data;
using DemoMVC.Models.Entities;
using DemoMVC.Models.Process;
using OfficeOpenXml;
using X.PagedList.Extensions;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DemoMVC.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;

        private ExcelProcess _excelProcess = new ExcelProcess();

        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _context.Person.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public IActionResult Index(int? page , int PageSize)
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem { Value = "3", Text = "3" },
                new SelectListItem { Value = "5", Text = "5" },
                new SelectListItem { Value = "10", Text = "10" },
                new SelectListItem { Value = "20", Text = "20" },
                new SelectListItem { Value = "25", Text = "25" },
                new SelectListItem { Value = "50", Text = "50" },
            };
            int pagesize =(PageSize =3);
            ViewBag.psize = pagesize;
            var model = _context.Person.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        // GET: Person
        [HttpPost]
        public async Task<IActionResult> Index(string keySearch)
        {
            var model = await _context.Person.Where(m => m.HoTen== keySearch).ToListAsync();
            return View(model);
        }

        // GET: Person/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Person/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,HoTen,QueQuan")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Person/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PersonId,HoTen,QueQuan")] Person person)
        {
            if (id != person.PersonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.PersonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Person/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var person = await _context.Person.FindAsync(id);
            if (person != null)
            {
                _context.Person.Remove(person);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(string id)
        {
            return _context.Person.Any(e => e.PersonId == id);
        }
        public IActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult>Upload(IFormFile file)
        {
            if (file!=null)
            {
                string fileExtension = Path.GetExtension(file.FileName);
                if (fileExtension != ".xls" && fileExtension != ".xlsx")
                {
                    ModelState.AddModelError("File", "Only Excel files are allowed");
                    
                }
                else
                {
                var fileName = DateTime.Now.ToShortTimeString() + fileExtension;
                var filePath = Path.Combine(Directory.GetCurrentDirectory()+ "/Upload/Excel", fileName);
                var fileLocation =  new FileInfo(filePath).ToString();
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                    var dt =_excelProcess.ExcelToDataTable(fileLocation);
                    for(int i=0 ; i<dt.Rows.Count; i++)
                    {
                        var ps = new Person {PersonId ="",HoTen="",QueQuan=""};
                        ps.PersonId = dt.Rows[i][0].ToString();
                        ps.HoTen = dt.Rows[i][1].ToString();
                        ps.QueQuan = dt.Rows[i][2].ToString();
                        _context.Add(ps);
                    }
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                }
            }
            return View();
        }
        public IActionResult Download()
        {
            var fileName = "Your FileName "+".xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("Sheet1");
                worksheet.Cells["A1"].Value = "PersonId";
                worksheet.Cells["B1"].Value = "HoTen";
                worksheet.Cells["C1"].Value = "QueQuan";
                var personList = _context.Person.ToList();
                worksheet.Cells["A2"].LoadFromCollection(personList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/nvd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }

    }
}

DemoMVC/Views/Person/Create.cshtml
@model DemoMVC.Models.Entities.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr>
    <form asp-action="Upload" enctype="multipart/form-data">
    <div class= "row form-control">
        <label class = "col-sm-2">Import data from Excel:</label>
        <input type ="file" name ="file" class="col-sm-4">
        <input type ="Submit" value ="Uploads" class = "btn btn-primary col-sm-1">
    </div>
    </form>
</hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QueQuan" class="control-label"></label>
                <input asp-for="QueQuan" class="form-control" />
                <span asp-validation-for="QueQuan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoMVC/Views/Person/Delete.cshtml
@model DemoMVC.Models.Entities.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QueQuan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoMVC/Views/Person/Details.cshtml
@model DemoMVC.Models.Entities.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QueQuan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PersonId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DemoMVC/Views/Person/Edit.cshtml
@model DemoMVC.Models.Entities.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonId" />
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QueQuan" class="control-label"></label>
                <input asp-for="QueQuan" class="form-control" />
                <span asp-validation-for="QueQuan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoMVC/Views/Person/Index.cshtml
@model IEnumerable<DemoMVC.Models.Entities.Person>
    @using X.PagedList;
    @using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-action ="Index">
    <input type="text" name ="keySearch" placeholder="Nhap Ho Ten">
    <input type ="submit" value ="Search">
</form>
<p>
    <a asp-action="Create">Create New</a>
    <a class = "btn btn-success" asp-action ="Download">Download</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QueQuan)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QueQuan)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PersonId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PersonId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PersonId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
@using (Html.BeginForm("Index","Person", FormMethod.Get,new {id ="form1"}))
{
    <div class = "row ">
        <div class ="col-md-11">
            @Html.PagedListPager((IPagedList) Model,page => Url.Action("Index",new {page=page,
    pageSize = ViewBag.psize}),
    new X.PagedList.Mvc.Core.PagedListRenderOptions {LiElementClasses = new string[] {"page - item"},
    PageClasses = new string[] {"page - link"}})
        </div>
        <div class = "col-md-1">
        @Html.DropDownList("pageSize",null,new {@class = "form - select"})
    </div>
    </div>
} 
<script src = "http:// code.jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function){
        $("#pageSize").change(function(){
            $("form1").submit();
        });
    });
</script>